//It’s responsible for taking a raw job description (the article_text) and turning it into a structured set of interview questions. It is highly optimized to save you money and time by using a Caching Layer—if someone else has already interviewed for this job URL, it doesn't call the AI again.

const { getAuth } = require('@clerk/express');
const Page = require("../models/Page");
const Question = require("../models/Question");

const { extractQuestionsWithLLM } = require("../utils/llmExtractor");
//ts job is to take the "raw" questions generated by your AI and turn them into a clean, searchable format.
const { normalizeQuestions } = require("../services/normalizerService");
//It’s the "Smart Saver." It checks if a question already exists in your database. If it does, it updates it; if not, it creates a new one.
const { upsertQuestions } = require("../services/questionService");
const log = require("../utils/logger");

exports.extractQuestions = async (req, res) => {
    const { userId } = getAuth(req);
    if (!userId) return res.status(401).json({ error: "Unauthorized" });

    const { url, article_text } = req.body;

    log.info("EXTRACT", `📄 Received extraction request for: ${url}`);
    log.info("EXTRACT", `📝 Article text length: ${article_text ? article_text.length : 0} chars`);

    if (!url || !article_text) {
        log.warn("EXTRACT", `Missing required fields — url: ${!!url}, article_text: ${!!article_text}`);
        return res.status(400).json({
            error: "url and article_text are required"
        });
    }

    try {

        /* 1️⃣ Check cache */
        log.info("EXTRACT", `🔍 Checking cache for URL: ${url}`);
        const existingPage = await Page.findOne({ page_url: url }).lean();

        if (existingPage) {

            const storedQuestions = await Question.find({
                _id: { $in: existingPage.question_ids }
            }).lean();

            log.success("EXTRACT", `💾 Cache HIT — returning ${storedQuestions.length} cached questions`);

            return res.json({
                message: "Cached",
                questions: storedQuestions
            });
        }

        log.info("EXTRACT", `🚫 Cache MISS — proceeding with LLM extraction`);

        /* 2️⃣ Extract questions using LLM */
        const candidateQuestions =
            await extractQuestionsWithLLM(article_text);

        if (!candidateQuestions || candidateQuestions.length === 0) {
            log.warn("EXTRACT", `No questions found in article`);
            return res.json({
                message: "No questions found",
                questions: []
            });
        }

        log.success("EXTRACT", `🤖 LLM extracted ${candidateQuestions.length} candidate questions`);

        /* 3️⃣ Normalize questions */
        const { normalizedMap, normalizedTexts } =
            normalizeQuestions(candidateQuestions);

        /* 3.5 Detect source domain */
        let sourceDomain = "unknown";

        try {
            sourceDomain = new URL(url).hostname;
        } catch { }

        log.info("EXTRACT", `🌐 Source domain: ${sourceDomain}`);

        /* 4️⃣ Insert / reuse questions in DB */
        const extractedQuestions =
            await upsertQuestions(normalizedMap, normalizedTexts, sourceDomain);

        /* 6️⃣ Save page */
        const newPage = new Page({
            page_url: url,
            raw_article_text: article_text,
            question_ids: extractedQuestions.map(q => q._id),
            source_site: sourceDomain
        });

        await newPage.save();
        log.success("EXTRACT", `📄 Page record saved for: ${url}`);

        /* 7️⃣ Response */
        log.success("EXTRACT", `✅ Extraction complete — ${extractedQuestions.length} questions saved for ${url}`);

        return res.json({
            message: "Extracted",
            questions: extractedQuestions
        });

    } catch (error) {

        log.error("EXTRACT", `Extraction failed for ${url}: ${error.message}`, error);

        return res.status(500).json({
            error: "Internal server error"
        });

    }
};